<?php

/**
 * @file
 * Contains utexas_flex_content_area.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function utexas_flex_content_area_theme($existing, $type, $theme, $path) {
  $variables = [
    'utexas_flex_content_area' => [
      'variables' => [
        'image' => NULL,
        'headline' => NULL,
        'copy' => NULL,
        'links' => [],
        'cta' => NULL,
      ],
      'template' => 'utexas-flex-content-area',
    ],
  ];
  return $variables;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_flex_content_area_form_layout_builder_update_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_flex_content_area_simplify_layout_form($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_flex_content_area_form_layout_builder_add_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_flex_content_area_simplify_layout_form($form);
}

/**
 * Helper function for Layout Builder form alters.
 */
function _utexas_flex_content_area_simplify_layout_form(&$form) {
  $map = [
    'default' => "Display two items per row.",
    'utexas_flex_content_area_1' => "Display one item per row.",
    'utexas_flex_content_area_3' => "Display three items per row.",
    'utexas_flex_content_area_4' => "Display four items per row.",
  ];
  if (isset($form['settings']['block_form'])) {
    $bundle = $form['settings']['block_form']['#block']->bundle();
    if ($bundle === 'utexas_flex_content_area') {
      foreach ($form['settings']['view_mode']['#options'] as $machine_name => $label) {
        if (in_array($machine_name, array_keys($map))) {
          $form['settings']['view_mode']['#options'][$machine_name] = $map[$machine_name];
        }
      }
    }
  }
}
