<?php

/**
 * @file
 * Contains install and update functions for the UTexas Call To Action module.
 */

/**
 * Implements hook_install().
 */
function utexas_call_to_action_install() {
  drupal_set_installed_schema_version('utexas_call_to_action', '8101');
}

/**
 * Change CTA widget and formatter to use utexas_link.
 */
function utexas_call_to_action_update_8101() {
  \Drupal::service('features.manager')->import([
    'utexas_call_to_action',
  ], TRUE);
}
