<?php

/**
 * @file
 * Defines custom paragraph type.
 */

/**
 * Implements hook_theme().
 */
function utexas_paragraph_promo_list_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_promo_list' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-promo-list',
    ],
    'field__paragraph__utexas_promo_list_container' => [
      'base hook' => 'field',
      'template' => 'field--paragraph--utexas-promo-list-container',
    ],
  ];
}

/**
 * Implements template_preprocesss_paragraph__PARAGRAPH_TYPE()
 *
 * For Promo List, provide linked or non-linked fields, depending on presence.
 */
function utexas_paragraph_promo_list_preprocess_paragraph__utexas_promo_list(&$variables) {
  $cta = $variables['paragraph']->get('field_utexas_pl_link')->getValue();
  $headline = $variables['paragraph']->get('field_utexas_pl_headline');
  $image = $variables['paragraph']->get('field_utexas_pl_image');
  $copy = $variables['paragraph']->get('field_utexas_pl_copy');
  $variables['image'] = $image->view('full');
  $variables['headline'] = $headline->view('full');
  $variables['copy'] = $copy->view('full');
  if (!empty($cta)) {
    $link_raw = $cta[0]['uri'];
    $linked_image = _utexas_paragraph_types_link_field($variables['image'], $link_raw);
    $variables['image'] = render($linked_image);
    $linked_headline = _utexas_paragraph_types_link_field($variables['headline'], $link_raw);
    $variables['headline'] = render($linked_headline);
  }
}
