<?php

/**
 * @file
 * Defines simple utexas_paragraph_quick_links field type.
 */

use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function utexas_paragraph_quick_links_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_quick_links' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-quick-links',
    ],
    'field__field_utexas_ql_links' => [
      'base hook' => 'field',
      'template' => 'field--utexas-ql-links',
    ],
  ];
}

/**
 * Implements hook_field_widget_form_alter().
 */
function utexas_paragraph_quick_links_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $field = $context['items']->getFieldDefinition();
  // If there is a QL instance present, proceed.
  if ($field->getName() === "field_flex_page_ql") {
    // If links field present on QL instance, proceed.
    if (isset($element['subform']['field_utexas_ql_links'])) {
      // If the links field is set to unlimited iterations, proceed.
      if ($element['subform']['field_utexas_ql_links']['widget']['#cardinality'] === FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED) {
        $element['subform']['field_utexas_ql_links']['widget']['add_more']['#value'] = t('Add Another Link');
      }
    }
  }
}
