<?php

/**
 * @file
 * Defines simple utexas_paragraph_quick_links field type.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function utexas_paragraph_quick_links_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_quick_links' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-quick-links',
    ],
    'field__field_utexas_ql_links' => [
      'base hook' => 'field',
      'template' => 'field--utexas-ql-links',
    ],
  ];
}

/**
 * Implements hook_field_widget_form_alter().
 */
function utexas_paragraph_quick_links_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $field = $context['items']->getFieldDefinition();
  if ($field->getName() == 'field_utexas_ql_links') {
    // Value used in hook_preprocess_field_multiple_value_form().
    $element['#utexas_ql_add_link_value'] = 'Add another link';
  }
}

/**
 * Implements hook_preprocess_field_multiple_value_form().
 *
 * We look for a value that was placed there earlier by
 * utexas_paragraph_resources_field_widget_form_alter() and
 * change the add_more button to use that.
 */
function utexas_paragraph_quick_links_preprocess_field_multiple_value_form(&$variables) {
  foreach (Element::children($variables['element']) as $child) {
    $child_element = &$variables['element'][$child];
    if (isset($child_element['#utexas_ql_add_link_value'])) {
      if (isset($child_element['#utexas_ql_add_link_value']) && isset($variables['element']['add_more']['#value']) && $variables['element']['add_more']['#value'] !== t('@add_another', ['@add_another' => $child_element['#utexas_ql_add_link_value']])) {
        $variables['element']['add_more']['#value'] = t('@add_another', ['@add_another' => $child_element['#utexas_ql_add_link_value']]);
      }
      if (isset($child_element['#utexas_ql_add_link_value']) && isset($variables['button']['#value']) && $variables['button']['#value'] !== t('@add_another', ['@add_another' => $child_element['#utexas_ql_add_link_value']])) {
        $variables['button']['#value'] = t('@add_another', ['@add_another' => $child_element['#utexas_ql_add_link_value']]);
      }
    }
  }
}
