<?php

/**
 * @file
 * Flex Page content type module file.
 *
 * Performs modifications that apply generally to the Flex Page content type.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function utexas_content_type_flex_page_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // 1. Act on all Flex Page forms to place selected widgets in vertical tabs.
  if (in_array($form_id, ['node_utexas_flex_page_form', 'node_utexas_flex_page_edit_form'])) {
    $widgets = [
      'field_flex_page_fca_a',
      'field_flex_page_fca_b',
      'field_flex_page_il_a',
      'field_flex_page_il_b',
      'field_flex_page_ql',
      'field_flex_page_pu',
      'field_flex_page_pca',
      'field_flex_page_resource',
    ];
    foreach ($widgets as $widget) {
      $title = isset($form[$widget]['widget']['title']['#value']) ? $form[$widget]['widget']['title']['#value'] : $form[$widget]['widget']['#title'];
      $form[$widget . '_base'] = [
        '#type' => 'details',
        '#title' => $title,
        '#group' => 'content',
      ];
      if ($form_id == 'node_utexas_flex_page_edit_form' && empty($form[$widget]['widget'][0])) {
        // Conditionally expand fields that already have data.
        $form[$widget . '_base']['#title'] = $title . ' (Empty)';
      }
      unset($form[$widget]['#group']);
      $form[$widget . '_base'][$widget] = $form[$widget];
      unset($form[$widget]);
    }
  }
}
