<?php

/**
 * @file
 * Defines additional configuration for utexas_paragraph_photo_content_area.
 */

/**
 * Implements hook_theme().
 */
function utexas_paragraph_photo_content_area_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_photo_content_area' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-photo-content-area',
    ],
    'field__paragraph__field_utexas_pca_credit' => [
      'base hook' => 'field',
      'template' => 'field--paragraph--field-utexas-pca-credit',
    ],
    'field__paragraph__field_utexas_pca_headline' => [
      'base hook' => 'field',
      'template' => 'field--paragraph--field-utexas-pca-headline',
    ],
  ];
}
