name: utdk8
recipe: drupal8
config:
  webroot: web
compose:
  - docker-compose.yml
services:
  pma:
    type: phpmyadmin
    hosts:
      - database
  appserver:
    overrides:
      # Avoid requiring a custom phpunit.xml file by passing overrides.
      # Based on https://github.com/lando/lando/pull/1092/files 
      # See also https://github.com/lando/lando/issues/360
      services:
         environment:
           SYMFONY_DEPRECATIONS_HELPER: 'disabled' # Temporary workaround to use deprecated methods.
           SIMPLETEST_DB: 'mysql://drupal8:drupal8@database/drupal8'
           SIMPLETEST_BASE_URL: 'http://utdk8.lndo.site/' # Alternately, Lando always makes available 'appserver' as domain.
           BROWSERTEST_OUTPUT_DIRECTORY: '/app/web/sites/simpletest/browser_output'
tooling:
  phpunit:
    service: appserver
    description: Run generic phpunit tests locally.
    cmd:
      - /app/vendor/bin/phpunit
  test: 
    service: appserver
    description: Run PHPUnit tests, with --group or --filter parameters
    cmd:
      - /app/vendor/bin/phpunit --configuration /app/web/core --stop-on-failure --verbose --debug --testsuite=functional,unit,kernel --printer="\Drupal\Tests\Listeners\HtmlOutputPrinter"
  test-js: 
    service: appserver
    description: Run FunctionalJavascript tests, with --group or --filter parameters
    cmd:
      - /app/vendor/bin/phpunit -c /app/web/profiles/utexas/tests/functional-js.phpunit.xml --stop-on-failure --testsuite=functional-javascript --verbose --debug