<?php

/**
 * @file
 * Wrapper module for all custom paragraph types.
 */

use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Helper function to create a link, provide field markup.
 *
 * @param mixed $field
 *   The Drupal render array for a given field.
 * @param string $link
 *   An internal or external link.
 *
 * @return mixed
 *   A render array of a Drupal link.
 */
function _utexas_paragraph_types_link_field($field, $link) {
  $link = Link::fromTextAndUrl($field, Url::fromUri($link));
  return $link->toRenderable();
}

/**
 * Implements hook_theme().
 */
function utexas_paragraph_types_theme($existing, $type, $theme, $path) {
  return [
    'field__utexas_headline' => [
      'base hook' => 'field',
      'template' => 'field--utexas-headline',
    ],
    'field__utexas_headline__underline' => [
      'base hook' => 'field',
      'template' => 'field--utexas-headline--underline',
    ],
    'field__utexas_copy' => [
      'base hook' => 'field',
      'template' => 'field--utexas-copy',
    ],
    'field__utexas_link_list' => [
      'base hook' => 'field',
      'template' => 'field--utexas-link-list',
    ],
    'field__utexas_link_list__darker' => [
      'base hook' => 'field',
      'template' => 'field--utexas-link-list--darker',
    ],
    'field__utexas_cta' => [
      'base hook' => 'field',
      'template' => 'field--utexas-cta',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function utexas_paragraph_types_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  $field_name = $variables['element']['#field_name'];
  // Add fields we want to use field--utexas-headline.twig.html.
  $headline_fields = [
    'field_utexas_fca_headline',
    'field_utexas_ql_headline',
    'field_utexas_pl_headline',
    'field_utexas_pca_headline',
    'field_utexas_resource_headline',
  ];
  // Add fields we want to use field--utexas-headline--underline.twig.html.
  $headline_fields_underline = [
    'field_utexas_plc_headline',
    'field_utexas_rc_title',
  ];
  // Add fields we want to use field--utexas-copy.twig.html.
  $copy_fields = [
    'field_utexas_fca_copy',
    'field_utexas_ql_copy',
    'field_utexas_pl_copy',
    'field_utexas_fh_copy',
    'field_utexas_pca_copy',
  ];
  // Add fields we want to use field--utexas-link-list.twig.html.
  $link_list_fields = [
    'field_utexas_fca_links',
    'field_utexas_pca_links',
    'field_utexas_ql_links',
  ];
  // Add fields we want to use field--utexas-link-list--darker.twig.html.
  $link_list_fields_darker = [
    'field_utexas_resource_links',
  ];
  // Add fields we want to use field--utexas-cta.twig.html.
  $cta_fields = [
    'field_utexas_fca_cta',
  ];

  if (in_array($field_name, $headline_fields)) {
    $suggestions[] = 'field__utexas_headline';
  }

  elseif (in_array($field_name, $headline_fields_underline)) {
    $suggestions[] = 'field__utexas_headline__underline';
  }

  elseif (in_array($field_name, $copy_fields)) {
    $suggestions[] = 'field__utexas_copy';
  }

  elseif (in_array($field_name, $link_list_fields)) {
    $suggestions[] = 'field__utexas_link_list';
  }

  elseif (in_array($field_name, $link_list_fields_darker)) {
    $suggestions[] = 'field__utexas_link_list__darker';
  }

  elseif (in_array($field_name, $cta_fields)) {
    $suggestions[] = 'field__utexas_cta';
  }
}
