<?php

/**
 * @file
 * Defines custom paragraph type.
 */

use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_theme().
 */
function utexas_paragraph_featured_highlight_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_featured_highlight' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-featured-highlight',
    ],
  ];
}

/**
 * Implements template_preprocesss_paragraph__PARAGRAPH_TYPE()
 *
 * For Featured Highlight, provide linked or non-linked title, depending on CTA.
 */
function utexas_paragraph_featured_highlight_preprocess_paragraph__utexas_featured_highlight(&$variables) {
  $headline = $variables['paragraph']->get('field_utexas_fh_headline')->getValue();
  if (!empty($headline)) {
    $title = $headline[0]['value'];
    $cta = $variables['paragraph']->get('field_utexas_fh_cta')->getValue();
    if (!empty($cta)) {
      $link_raw = $cta[0]['uri'];
      $linked_title = Link::fromTextAndUrl($title, Url::fromUri($link_raw));
      $title = $linked_title->toRenderable();
    }
    // If no headline is present, this variable won't be sent to the template.
    $variables['processed_headline'] = render($title);
  }
}
