<?php

/**
 * @file
 * Contains utexas_card.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function utexas_card_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the utexas_card module.
    case 'help.page.utexas_card':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UTexas Card') . '</p>';
      return $output;

    default:
  }
}
