<?php

/**
 * @file
 * Contains utexas_card.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function utexas_card_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the utexas_card module.
    case 'help.page.utexas_card':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UTexas Card') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function utexas_card_theme($existing, $type, $theme, $path) {
  return [
    'field__field_card_instance' => [
      'base hook' => 'field',
    ],
    'field__paragraph__field_card_links__card_instance' => [
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_preprocess_field().
 */
function utexas_card_preprocess_field(&$variables) {
  $field_name = $variables['element']['#field_name'];
  // kint($field_name);
  if ($field_name == 'field_ut_card_cta') {
    $variables['items'][0]['content']['#options']['attributes']['class'][] = 'cta';
  }
  if ($field_name == 'field_ut_card_links') {
    $items = $variables['items'];
    foreach ($items as $key => $value) {
      $variables['items'][$key]['content']['#options']['attributes']['class'][] = 'utexas-card-link';
    }
  }
}
