<?php

/**
 * @file
 * Quick Links custom compound field dot module file.
 */

 use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function utexas_quick_links_theme($existing, $type, $theme, $path) {
  $variables = [
    'utexas_quick_links' => [
      'variables' => [
        'headline' => NULL,
        'copy' => NULL,
        'links' => [],
        'columns' => NULL,
      ],
      'template' => 'utexas-quick-links',
    ],
  ];
  return $variables;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_quick_links_form_layout_builder_update_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_quick_links_simplify_layout_form($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_quick_links_form_layout_builder_add_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_quick_links_simplify_layout_form($form);
}

/**
 * Helper function for Layout Builder form alters.
 */
function _utexas_quick_links_simplify_layout_form(&$form) {
  $map = [
    'default' => "Display links in 1 column",
    'utexas_quick_links_2' => "Display links in 2 columns",
    'utexas_quick_links_3' => "Display links in 3 columns",
    'utexas_quick_links_4' => "Display links in 4 columns",
  ];
  if (isset($form['settings']['block_form'])) {
    $bundle = $form['settings']['block_form']['#block']->bundle();
    if ($bundle === 'utexas_quick_links') {
      foreach ($form['settings']['view_mode']['#options'] as $machine_name => $label) {
        if (in_array($machine_name, array_keys($map))) {
          $form['settings']['view_mode']['#options'][$machine_name] = $map[$machine_name];
        }
      }
    }
  }
}
