<?php

/**
 * @file
 * Proprocess settings for available layout configuration.
 */

/**
 * Implements hook_preprocess_layout().
 */
function utexas_layouts_preprocess_layout(&$variables) {
  if (isset($variables['content']['#background_image'])) {
    // Send background image to the template as a separate variable.
    $variables['background_image'] = $variables['content']['#background_image'];
  }
}
