version: 2
jobs:
  build:
    working_directory: ~/site_build
    docker:
      - image: circleci/php:7.2-apache-node-browsers
        environment:
          - MYSQL_HOST=127.0.0.1
          - BROWSERTEST_OUTPUT_DIRECTORY=/var/www/site_build/web/sites/simpletest/browser_output
          - SIMPLETEST_BASE_URL=http://localhost:8080
          - SIMPLETEST_DB=mysql://root:ubuntu@127.0.0.1:3306/circle_test
          - SYMFONY_DEPRECATIONS_HELPER=disabled
      - image: mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=circle_test
          - MYSQL_ROOT_HOST=%
    steps:
      - checkout
      # Begin envionment setup.
      # Run apt-get update before installing any packages with apt.
      # Install required dependencies.
      - run:
          name: Apt Get Update
          command: sudo apt-get update
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Install libpng extension
          command: sudo apt-get install -y libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - run:
          name: Install Composer
          command: 'curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer'
      - run:
          name: Install mysql-client
          command: sudo apt-get install mysql-client
      - run:
          name: Configure shell
          command: |
            echo -e "Host github.austin.utexas.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            echo 'export PATH=/var/www/site_build/vendor/bin:$PATH' >> $BASH_ENV
      - run: 
          name: Configure Drush
          command: |
            mkdir ~/.drush
            cp .circleci/fixtures/aliases.drushrc.php ~/.drush/aliases.drushrc.php
      - run: 
          name: Configure docroot
          command: sudo mv /home/circleci/site_build /var/www/site_build
      # Set up script creates docroot - run before vhost configuration so the docroot is present.    
      - run: 
          name: Set up and install Drupal
          command: |
            cd /var/www/site_build
            bash setup.sh
      # Modifications to envars required to make Apache run as circle user.
      # Project must be checked out into home directory - move code to more conventional directory for Apache.     
      - run: 
          name: Configure Apache and vhost
          command: | 
            sudo cp /var/www/site_build/.circleci/fixtures/circle-vhost.conf /etc/apache2/sites-available
            sudo cp /var/www/site_build/.circleci/fixtures/envvars /etc/apache2/envvars
            sudo a2ensite circle-vhost.conf
            sudo a2enmod rewrite
            sudo service apache2 restart
      # Ensure vhost is setup correctly before proceeding.
      #- run: 
      #  name: Vhost setup smoke test.
      #   command: |
      #     HTTP_STATUS=$(curl -I -s  http://localhost:8080 | grep HTTP)
      #     echo "$HTTP_STATUS"
      #     if [[ "$HTTP_STATUS" != *"200"* ]]; then
      #       exit 1
      #     fi
      - run: 
          name: Prepare HTML output directory for testing.
          command: |
            if [ ! -d /var/www/site_build/web/sites/simpletest/browser_output ]; then
              mkdir -p /var/www/site_build/web/sites/simpletest/browser_output
            fi
            chmod -R 774 /var/www/site_build/web/sites/simpletest
      - run:
         name: Start chromedriver.
         command: chromedriver --whitelisted-ips=127.0.0.1 --headless
         background: true
      - run:
         name: Copy custom modules for testing.
         command: |
           if [ ! -d /var/www/site_build/web/modules/contrib ]; then
              mkdir -p /var/www/site_build/web/modules/contrib
           fi
           cp -r /var/www/site_build/web/profiles/utexas/modules/composer_managed/custom/utexas_breadcrumbs_visibility /var/www/site_build/web/modules/contrib/utexas_breadcrumbs_visibility

      # Begin testing.
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-results
            cd /var/www/site_build
            vendor/bin/phpunit -c /var/www/site_build/.circleci/fixtures/functional-js.phpunit.xml --stop-on-failure --testsuite=functional-javascript --verbose --debug --group=utexas
            vendor/bin/phpunit -c /var/www/site_build/web/core/phpunit.xml.dist --stop-on-failure --testsuite=functional --verbose --debug --group=utexas
       
      # Save artifacats.
      - store_artifacts:
          path: /tmp/test-results
          destination: PHPUnit  
      - store_artifacts:
          path: /var/www/site_build/web/sites/simpletest
          destination: SimpleTest
      - store_artifacts:
          path: /var/www/site_build/web/sites/simpletest/browser_output
          destination: FunctionalJavascript
