version: 2
jobs:
  build:
    working_directory: ~/site_build
    docker:
      # "Browsers" container image includes unnecessary components and won't allow for apache to run on port 80.
      # See https://circleci.com/docs/2.0/circleci-images/ for documentation about Pre-Built CircleCI Docker Images. 
      - image: circleci/php:7.1-apache
        environment:
          - MYSQL_HOST=127.0.0.1
      - image: mysql:5.7
        environment:
          - MYSQL_USER=root
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=circle_test
          - MYSQL_ROOT_HOST=%
    steps:
      - checkout
      # Run apt-get update before installing any packages with apt.
      # Install required dependencies. 
      - run:
          name: Apt Get Update
          command: sudo apt-get update
      - run:
          name: Install PHP extensions
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Install libpng extension
          command: sudo apt-get install -y libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - run:
          name: Install Composer
          command: 'curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer'
      - run:
          name: Install mysql-client
          command: sudo apt-get install mysql-client
          
      - run:
          name: Configure shell
          command: |
            echo -e "Host github.austin.utexas.edu\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            echo 'export PATH=/var/www/site_build/vendor/bin:$PATH' >> $BASH_ENV
            
      - run: 
          name: Configure Drush
          command: |
            mkdir ~/.drush
            cp .circleci/fixtures/aliases.drushrc.php ~/.drush/aliases.drushrc.php
            
      - run: 
          name: Configure docroot
          command: sudo mv /home/circleci/site_build /var/www/site_build
       
      # Set up script creates docroot - run before vhost configuration so the docroot is present.    
      - run: 
          name: Set up and install Drupal
          command: |
            cd /var/www/site_build
            bash setup.sh
            cp .circleci/fixtures/settings.php /var/www/site_build/web/sites/default/settings.local.php
            drush @test si utexas --site-name="Drupal Kit Rocks" install_configure_form.enable_update_status_module=NULL -y
            drush @test en simpletest -y
      
      # Modifications to envars required to make Apache run as circle user.
      # Project must be checked out into home directory - move code to more conventional directory for Apache.     
      - run: 
          name: Configure Apache and vhost
          command: | 
            sudo cp /var/www/site_build/.circleci/fixtures/circle-vhost.conf /etc/apache2/sites-available
            sudo cp /var/www/site_build/.circleci/fixtures/envvars /etc/apache2/envvars
            sudo a2ensite circle-vhost.conf
            sudo a2enmod rewrite
            sudo service apache2 restart

      - run: 
         name: Vhost setup smoke test
         command: |
           HTTP_STATUS=$(curl -I -s  http://localhost:8080/user/login | grep HTTP)
           echo "$HTTP_STATUS"
           if [[ "$HTTP_STATUS" != *"200"* ]]; then
             exit 1
           fi
                                 
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-results
            cd /var/www/site_build/web
            php core/scripts/run-tests.sh PHPUnit --dburl mysql://root:ubuntu@127.0.0.1:3306/circle_test --url http://localhost:8080 --module utexas --verbose --color --xml /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: PHPUnit
          
      - store_artifacts:
          path: /var/www/site_build/web/sites/simpletest
          destination: SimpleTest
