<?php

/**
 * @file
 * Contains utexas_media_types.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function utexas_media_types_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the utexas_media_types module.
    case 'help.page.utexas_media_types':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Media Types for use in the UTDK distribution.') . '</p>';
      return $output;

    default:
  }
}
