<?php

/**
 * @file
 * Contains utexas_media_types.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

use Drupal\utexas_media_types\IframeTitleHelper;

/**
 * Implements hook_help().
 */
function utexas_media_types_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the utexas_media_types module.
    case 'help.page.utexas_media_types':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Media Types for use in the UTDK distribution.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function utexas_media_types_theme() {
  return [
    'field__field_media_oembed_video' => [
      'template' => 'field--field-media-oembed-video',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function utexas_media_types_page_attachments(array &$attachments) {
  // Resolve issue in
  // https://github.austin.utexas.edu/eis1-wcs/utdk_profile/issues/1395.
  $attachments['#attached']['library'][] = 'utexas_media_types/media-oembed';
}

/**
 * Implements template_preprocess_media_oembed_iframe().
 */
function utexas_media_types_preprocess_media_oembed_iframe(array &$variables) {
  /** @var \Drupal\media\OEmbed\Resource $resource */
  $resource = $variables['resource'];
  $media = $variables['media'];
  $html_dom = Html::load($media);
  $iframes = $html_dom->getElementsByTagName('iframe');
  foreach ($iframes as $iframe) {
    $iframe->setAttribute('title', IframeTitleHelper::getTitle($resource));
  }
  $variables['media'] = Html::serialize($html_dom);
}

/**
 * Implements hook_form_alter().
 */
function utexas_media_types_form_alter(&$form, $form_state, $form_id) {
  // Add a suggestion to document upload forms to use a file-sharing service.
  $forms_to_admonish = [
    'media_utexas_document_add_form',
    'views_form_media_library_widget_utexas_document',
    'views_form_media_library_widget_table_utexas_document',
  ];
  if (in_array($form_id, $forms_to_admonish)) {
    \Drupal::messenger()->addWarning(t('For non-image documents such as PDFs, MS Office documents, or high-resolution images intended for download, consider using a third-party file sharing service instead of uploading to the Media Library. See <a href="@url" target="_blank">this KB article<span class="ut-cta-link--external"></span></a> for additional information.', ['@url' => 'https://ut.service-now.com/sp?id=kb_article&number=KB0019227']));
  }
}
