<?php

/**
 * @file
 * Contains utexas_media_types.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Html;

use Drupal\utexas_media_types\IframeTitleHelper;

/**
 * Implements hook_help().
 */
function utexas_media_types_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the utexas_media_types module.
    case 'help.page.utexas_media_types':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides Media Types for use in the UTDK distribution.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function utexas_media_types_theme() {
  return [
    'field__field_media_oembed_video' => [
      'template' => 'field--field-media-oembed-video',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function utexas_media_types_page_attachments(array &$attachments) {
  // Resolve issue in
  // https://github.austin.utexas.edu/eis1-wcs/utdk_profile/issues/1395.
  $attachments['#attached']['library'][] = 'utexas_media_types/media-oembed';
}

/**
 * Implements template_preprocess_media_oembed_iframe().
 */
function utexas_media_types_preprocess_media_oembed_iframe(array &$variables) {
  /** @var \Drupal\media\OEmbed\Resource $resource */
  $resource = $variables['resource'];
  $media = $variables['media'];
  $html_dom = Html::load($media);
  $iframes = $html_dom->getElementsByTagName('iframe');
  foreach ($iframes as $iframe) {
    $iframe->setAttribute('title', IframeTitleHelper::getTitle($resource));
  }
  $variables['media'] = Html::serialize($html_dom);
}
