<?php

/**
 * @file
 * Quick Links custom compound field dot module file.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\block\BlockForm;

/**
 * Implements hook_theme().
 */
function utexas_quick_links_theme($existing, $type, $theme, $path) {
  $variables = [
    'utexas_quick_links' => [
      'variables' => [
        'headline' => NULL,
        'copy' => NULL,
        'links' => [],
        'columns' => NULL,
      ],
      'template' => 'utexas-quick-links',
    ],
  ];
  return $variables;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_quick_links_form_layout_builder_update_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_quick_links_simplify_layout_form($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_quick_links_form_layout_builder_add_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_quick_links_simplify_layout_form($form);
}

/**
 * Helper function for Layout Builder form alters.
 */
function _utexas_quick_links_simplify_layout_form(&$form) {
  $is_quick_links = FALSE;
  // Check inline block view mode labels.
  if (isset($form['settings']['block_form'])) {
    $bundle = $form['settings']['block_form']['#block']->bundle();
    if ($bundle === 'utexas_quick_links') {
      $is_quick_links = TRUE;
    }
  }
  // Check reusable block view mode labels.
  if (isset($form['settings']['provider'])) {
    if ($form['settings']['provider']['#value'] == 'block_content') {
      $options = array_keys($form['settings']['view_mode']['#options']);
      if (in_array('utexas_quick_links_2', $options)) {
        $is_quick_links = TRUE;
      }
    }
  }
  if ($is_quick_links) {
    $form['settings']['view_mode']['#options'] = _update_quick_links_view_mode_labels($form['settings']['view_mode']['#options']);
  }
}

/**
 * Helper function for updating view mode labels.
 */
function _update_quick_links_view_mode_labels($options) {
  $formatterManager = \Drupal::service('plugin.manager.field.formatter');
  $definitions = $formatterManager->getDefinitions();
  $map = _utexas_quick_links_mapping_formatter_labels($definitions, 'utexas_quick_links');
  // Use keys from the available $options to get the matching key-value pairs.
  return array_intersect_key($map, $options);
}

/**
 * Helper function for generating a mapped array of the widget formatter labels.
 */
function _utexas_quick_links_mapping_formatter_labels($definitions, $widget_type) {
  $map = [];
  foreach ($definitions as $key => $value) {
    if (strpos($key, $widget_type) !== FALSE) {
      $map[$key] = $definitions[$key]['label']->__toString();
    }
  }
  // Convert first key to "default" to be used by view modes.
  $map['default'] = $map[$widget_type];
  unset($map[$widget_type]);
  // Sort the array by machine name.
  asort($map);
  return $map;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add logic to the place block form.
 */
function utexas_quick_links_form_block_form_alter(&$form, &$form_state, $form_id) {
  $bundle = FALSE;
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof BlockForm) {
    /** @var \Drupal\block\Entity\Block $entity */
    $entity = $form_object->getEntity();
    // Verify this is a content block.
    if ($entity->getEntityType()->getGroup() == 'content') {
      $uuid = $entity->getPlugin()->getDerivativeId();
      /** @var Drupal\block_content\Entity\BlockContent $block_content */
      if (isset($uuid)) {
        $block_content = \Drupal::service('entity.repository')->loadEntityByUuid('block_content', $uuid);
        $bundle = $block_content->bundle();
        if ($bundle == 'utexas_quick_links') {
          $form['settings']['view_mode']['#options'] = _update_quick_links_view_mode_labels($form['settings']['view_mode']['#options']);
        }
      }
    }
  }
}
