#!/usr/bin/env bash

PHP_LIST=$( git diff --name-only --cached --diff-filter=ACM -- '*.php' '*.inc' '*.yml' '*.module' '*.install')
CSS_LIST=$( git diff --name-only --cached --diff-filter=ACM -- '*.css')
GIT_ROOT="$(git rev-parse --show-toplevel)"
PHPCS_BIN=../../../vendor/bin/phpcs
RULESET=../../../vendor/drupal/coder/coder_sniffer/DrupalPractice/ruleset.xml
PHP_STAN_BIN=../../../vendor/bin/phpstan
STYLELINTER=/node_modules/.bin/stylelint

if [ ! -f "$GIT_ROOT""$STYLELINTER" ]; then
    echo "WARNING: Stylelint was not found. Fix this by running 'npm install' in the repository root."
    exit 1
fi

if [ ! -f "$PHP_STAN_BIN" ]; then
    echo "WARNING: PHPStan was not found. You probably need to run 'composer install'."
    exit 1
fi

if [ ! -f "$PHPCS_BIN" ]; then
    echo "WARNING: PHPCS was not found. You probably need to run 'composer install'."
    exit 1
fi

echo "To bypass pre-commit checks, add '--no-verify' to your commit command"


composer validate --no-check-all --strict

# If a composer violation has been found, exit without further sniffing
if [[ $? -ne 0 ]] ; then
    exit 1
fi

if [ ! -z "$PHP_LIST" ]; then
    # PHP linting
    "$PHPCS_BIN" --standard="$RULESET" ${PHP_LIST}
fi

# If a PHPCS violation has been found, exit without further sniffing
if [[ $? -ne 0 ]] ; then
    exit 1
fi

if [ ! -z "$PHP_LIST" ]; then
    # PHP static analysis
    "$PHP_STAN_BIN" analyse ${PHP_LIST}
fi

# If a PHPStan violation has been found, exit without further sniffing
if [[ $? -ne 0 ]] ; then
    exit 1
fi

if [ ! -z "$CSS_LIST" ]; then
    # CSS linting
    "$GIT_ROOT""$STYLELINTER" ${CSS_LIST}
fi

if [[ $? -ne 0 ]] ; then
    exit 1
fi
