<?php

/**
 * @file
 * UT News base module installation file.
 */

/**
 * Implements hook_update_dependencies().
 */
function utnews_update_dependencies() {
  // Stipulate order of update hooks.
  $dependencies['utnews'][8103] = [
    'utexas' => 11007,
  ];
  return $dependencies;
}

/**
 * Implements hook_install().
 */
function utnews_install() {
  // Enable this feature's read-only functionality. We do this in a
  // hook_install() implementation so that the module may be uninstalled.
  if (\Drupal::moduleHandler()->moduleExists('utnews_readonly') === FALSE) {
    \Drupal::service('module_installer')->install(['utnews_readonly']);
  }
  // Enable this feature's dynamic overrides module. We do this here so that the
  // module may be uninstalled.
  if (\Drupal::moduleHandler()->moduleExists('utnews_overrides') === FALSE) {
    \Drupal::service('module_installer')->install(['utnews_overrides']);
  }

  // Add configuration for scheduled transitions.
  $config = \Drupal::configFactory()->getEditable('scheduled_transitions.settings');
  $bundles = $config->get('bundles') ?? [];
  $news_bundle = ['entity_type' => 'node', 'bundle' => 'utnews_news'];
  if (!in_array($news_bundle, $bundles)) {
    $bundles[] = $news_bundle;
    $config->set('bundles', $bundles)->save();
  }
}

/**
 * Enable the utnews_readonly module.
 */
function utnews_update_8101() {
  // Enable this features read-only functionality.
  if (\Drupal::moduleHandler()->moduleExists('utnews_readonly') === FALSE) {
    \Drupal::service('module_installer')->install(['utnews_readonly']);
  }
}

/**
 * Enable utnews_overrides by default on new & existing sites (#195).
 */
function utnews_update_8102() {
  // Enable this features overrider functionality.
  if (\Drupal::moduleHandler()->moduleExists('utnews_overrides') === FALSE) {
    \Drupal::service('module_installer')->install(['utnews_overrides']);
  }
}

/**
 * Add configuration for scheduled transitions. (#3222).
 */
function utnews_update_8103() {
  // Add configuration for scheduled transitions.
  $config = \Drupal::configFactory()->getEditable('scheduled_transitions.settings');
  $bundles = $config->get('bundles') ?? [];
  $news_bundle = ['entity_type' => 'node', 'bundle' => 'utnews_news'];
  if (!in_array($news_bundle, $bundles)) {
    $bundles[] = $news_bundle;
    $config->set('bundles', $bundles)->save();
  }
}
