<?php

/**
 * @file
 * Provides the base content type component for the News add-on.
 */

use Drupal\utnews\Permissions;

/**
 * Implements hook_modules_installed().
 */
function utnews_modules_installed($modules, $is_syncing) {
  if (in_array('utexas_scheduled_transitions', $modules)) {
    utnews_configure_scheduled_transitions();
  }
}

/**
 * Helper function registers utnews_news bundle with Scheduled Transitions.
 */
function utnews_configure_scheduled_transitions() {
  // Add configuration for scheduled transitions.
  $config = \Drupal::configFactory()->getEditable('scheduled_transitions.settings');
  $bundles = $config->get('bundles') ?? [];
  $news_bundle = ['entity_type' => 'node', 'bundle' => 'utnews_news'];
  if (!in_array($news_bundle, $bundles)) {
    $bundles[] = $news_bundle;
    $config->set('bundles', $bundles)->save();
  }

  // Add scheduling permissions to all roles that can create News content.
  $roles = Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  /** @var Drupal\user\Entity\Role $role */
  foreach ($roles as $role_id => $role) {
    $role_permissions = $role->getPermissions();
    foreach ($role_permissions as $permission) {
      if ($permission == 'create utnews_news content') {
        Permissions::assignPermissions('editor', $role_id);
        Drupal::messenger()->addMessage(t('News scheduling permissions set for %role role.', [
          '%role' => $role->label(),
        ]));
      }
    }
  }
}
