<?php

/**
 * @file
 * Contains utexas_homepage_alert.module.
 */

use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_theme().
 */
function utexas_site_announcement_theme() {
  return [
    'utexas_site_announcement' => [
      'variables' => [
        'title' => NULL,
        'header_id' => NULL,
        'icon' => NULL,
        'message' => NULL,
        'cta' => NULL,
        'background_color' => NULL,
        'text_color' => NULL,
        'unique_id' => NULL,
      ],
      'template' => 'utexas-site-announcement',
    ],
  ];
}

/**
 * Prepares variables for emergency templates.
 *
 * Default template: emergency.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the emergency information and
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function utexas_site_announcement_preprocess_utexas_site_announcement(array &$variables): void {
  $url = Url::fromRoute('utexas_announcement.configuration');
  if (\Drupal::currentUser()->hasPermission('manage utexas site announcement')) {
    $link = Link::fromTextAndUrl(t('Update this announcement'), $url);
    $link = $link->toRenderable();
    $link['#attributes'] = [
      'class' => [
        'ut-btn--secondary',
      ],
    ];
    $variables['edit_link'] = $link;
  }
}
