#!/usr/bin/env bash

PHP_LIST=$( git diff --name-only --cached --diff-filter=ACM -- '*.php' '*.inc' '*.yml' '*.module' '*.install')
GIT_ROOT="$(git rev-parse --show-toplevel)"
PHPCS_BIN=/vendor/bin/phpcs
RULESET=/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml
PHP_STAN_BIN=/vendor/bin/phpstan

if [ ! -f "$GIT_ROOT""$PHPCS_BIN" ];
  then
    echo "WARNING: PHP Code Sniffer was not found. This commit might include coding standards violations. You can fix this by ensuring that composer has correctly installed it's dev dependencies including a symlink in the bin folder to the phpcs package in vendor."
    exit 1
  else
    echo "Sniffing staged files via PHP Code Sniffer."
    echo "To bypass this check, add '--no-verify' to your commit command"
fi

if [ ! -z "$PHP_LIST" ];
  then
    # Code sniffer (syntax)
    "$GIT_ROOT""$PHPCS_BIN" --standard="$GIT_ROOT""$RULESET" ${PHP_LIST}
    # Static analysis
    "$GIT_ROOT""$PHP_STAN_BIN" analyse ${PHP_LIST}
fi

# If a PHPCS violation has been found, exit without CSS sniffing
if [[ $? -ne 0 ]] ; then
    exit 1
fi

# Stylelinting is run separately.
STYLELINTER=node_modules/.bin/stylelint
if [ ! -f $STYLELINTER ];
  then
    echo "WARNING: Stylelint was not found. This commit might include coding standards violations. You can fix this by running `npm install` in the repository root."
    exit 1
  else
    echo "Linting staged files via Stylelint."
    echo "To bypass this check, add '--no-verify' to your commit command"
fi

CSS_LIST=$( git diff --name-only --cached --diff-filter=ACM -- '*.css')
if [ ! -z "$CSS_LIST" ];
  then
    $STYLELINTER ${CSS_LIST}
fi

if [[ $? -ne 0 ]] ; then
    exit 1
fi
