<?php

/**
 * @file
 * Defines utexas_link_element field type.
 */

/**
 * Implements hook_theme().
 */
function utexas_form_elements_theme($existing, $type, $theme, $path) {
  $variables = [
    'utexas_link_element' => [
      'render element' => 'element',
      'template' => 'utexas-link-element',
    ],
  ];
  return $variables;
}

/**
 * Implements hook_field_widget_info_alter().
 */
function utexas_form_elements_field_widget_info_alter(array &$definitions) {
  $definitions['options_buttons']['class'] = 'Drupal\utexas_form_elements\Plugin\Field\FieldWidget\OptionsButtonsWidget';
}
