<?php

/**
 * @file
 * UTexas Beacon module.
 *
 * This module collects data from an installation of the UTexas distribution
 * and sends it to stewards daily on cron runs.
 */

/**
 * URI of endpoint for site data.
 */

use Drupal\Component\Serialization\Json;
use GuzzleHttp\Exception\RequestException;

/**
 * Implements hook_mail().
 *
 * Prepare a message based on parameters; called from drupal_mail().
 */
function utexas_beacon_mail($key, &$message, $email_params) {
  switch ($key) {
    case 'information':
      $message['subject'] = $email_params['subject'];
      $message['headers']['Content-Type'] = 'text/plain; charset=UTF-8; format=flowed';
      $message['body'][] = $email_params['body'];
      break;
  }
}

/**
 * Builds array of site info.
 */
function _utexas_beacon_prepare_data() {

  // Build site information.
  $site_config = \Drupal::config('system.site');
  $site_data = [];
  $site_data['site_name'] = $site_config->get('name');
  $site_data['base_url'] = $GLOBALS['base_url'];
  $site_data['ip_address'] = \Drupal::request()->getClientIp();
  $site_data['hostname'] = gethostname();
  $site_data['admin_email'] = $site_config->get('mail');
  $site_data['drupal_version'] = Drupal::VERSION;
  $site_data['php_version'] = phpversion();
  $site_data['http_host'] = $_SERVER['HTTP_HOST'] ?? 'N/A';
  $site_data['logname'] = $_SERVER['LOGNAME'] ?? 'N/A';
  $site_data['request_uri'] = $_SERVER['REQUEST_URI'] ?? 'N/A';
  $site_data['pantheon_site_name'] = $_SERVER['PANTHEON_SITE_NAME'] ?? 'N/A';

  // Installation profile information.
  $active_profile = \Drupal::installProfile();
  /** @var \Drupal\Core\Extension\ProfileExtensionList $extension_list_profile_service */
  $extension_list_profile_service = \Drupal::service('extension.list.profile');
  $profile_information = $extension_list_profile_service->getExtensionInfo($active_profile);
  $site_data['active_installation_profile_distribution_name'] = $profile_information['name'];
  $site_data['active_installation_profile_version'] = $profile_information['version'];

  // Theme information.
  $site_data['current_theme'] = \Drupal::configFactory()->getEditable('system.theme')->get('default', 'machine_name');
  if ($site_data['current_theme'] == 'forty_acres') {
    /** @var \Drupal\Core\Extension\ThemeExtensionList $extension_list_theme_service */
    $extension_list_theme_service = \Drupal::service('extension.list.theme');
    $forty_acres_info = $extension_list_theme_service->getExtensionInfo($site_data['current_theme']);
    $site_data['forty_acres_version'] = $forty_acres_info['version'];
  }

  // Module information.
  $moduleHandler = \Drupal::service('module_handler');
  if ($moduleHandler->moduleExists('google_tag')) {
    $config = \Drupal::config('google_tag.settings');
    $site_data['google_tag_manager_code'] = $config->get('container_id') ?? '';
  }
  if ($moduleHandler->moduleExists('google_cse')) {
    $config = \Drupal::config('search.page.google_cse_search');
    $site_data['google_cse_id'] = $config->get('configuration')['cx'] ?? '';
  }
  return $site_data;
}

/**
 * Implements hook_cron().
 *
 * Prepares info and posts data via guzzle or sends email via
 * drupal_mail() once a day.
 */
function utexas_beacon_cron() {
  // Retrieve time of last cron run, or default to timestamp of 1 day in past.
  $cron_last = \Drupal::state()->get('system.cron_last', time() - 24 * 60 * 60);
  // $cron_day is the midnight-time of the day that the last cron ran.
  $cron_day = strtotime('0:00', $cron_last);
  // $today is the midnight-time of the current day.
  $today = strtotime('0:00', time());
  // Only send data once a day.
  if ($cron_last && $today > $cron_day) {
    $site_data_for_post = _utexas_beacon_prepare_data();
    // Prepare the data.
    $encoded_data = Json::encode($site_data_for_post);
    $utexas_beacon_settings = \Drupal::config('utexas_beacon.settings');
    $headers = [
      'X-UTexas-Beacon-Key' => $utexas_beacon_settings->get('utexas_beacon_key'),
      'Content-Type' => 'application/json',
    ];

    // Post the site data.
    $client = \Drupal::httpClient();
    try {
      // Use 'debug' => true for more info.
      $endpoint_uri = \Drupal::state()->get('utexas_beacon_endpoint_uri') ?? 'https://drupal-beacon.its.utexas.edu/beacon-end.php';
      $client->post($endpoint_uri, [
        'headers' => $headers,
        'body' => $encoded_data,
      ]);
      \Drupal::logger('utexas_beacon')->notice('Beacon data logged to ITS Drupal Team.');
    }
    catch (RequestException $e) {
      \Drupal::logger('utexas_beacon')->error($e);
    }
  }
}
