<?php

/**
 * @file
 * Defines utexas_paragraph_image_link field type.
 */

/**
 * Implements hook_theme().
 */
function utexas_paragraph_image_link_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_image_link' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-image-link',
    ],
  ];
}

/**
 * Implements hook_preprocess_paragraph().
 */
function utexas_paragraph_image_link_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() == 'utexas_image_link') {
    $variables['link'] = FALSE;
    if ($link = $variables['paragraph']->get('field_utexas_il_link')->getValue()) {
      // Pass the URI of the Image Link's link field to the paragraph template.
      $variables['link'] = $link[0]['uri'];
    }
  }
}
