<?php

/**
 * @file
 * Defines simple utexas_paragraph_flex_content_area field types.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function utexas_paragraph_flex_content_area_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_flex_content_area' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-flex-content-area',
    ],
    'field__paragraph__utexas_fca_container' => [
      'base hook' => 'field',
      'template' => 'field--paragraph--utexas-fca-container',
    ],
  ];
}

/**
 * Implements hook_field_widget_form_alter().
 */
function utexas_paragraph_flex_content_area_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $field = $context['items']->getFieldDefinition();
  if ($field->getName() == 'field_utexas_fca_links') {
    // Value used in hook_preprocess_field_multiple_value_form().
    $element['#utexas_fca_add_link_value'] = 'Add another link';
  }
}

/**
 * Implements hook_preprocess_field_multiple_value_form().
 *
 * We look for a value that was placed there earlier by
 * utexas_paragraph_resources_field_widget_form_alter() and
 * change the add_more button to use that.
 */
function utexas_paragraph_flex_content_area_preprocess_field_multiple_value_form(&$variables) {
  foreach (Element::children($variables['element']) as $child) {
    $child_element = &$variables['element'][$child];
    if (isset($child_element['#utexas_fca_add_link_value'])) {
      if (isset($child_element['#utexas_fca_add_link_value']) && isset($variables['element']['add_more']['#value']) && $variables['element']['add_more']['#value'] !== t('@add_another', ['@add_another' => $child_element['#utexas_fca_add_link_value']])) {
        $variables['element']['add_more']['#value'] = t('@add_another', ['@add_another' => $child_element['#utexas_fca_add_link_value']]);
      }
      if (isset($child_element['#utexas_fca_add_link_value']) && isset($variables['button']['#value']) && $variables['button']['#value'] !== t('@add_another', ['@add_another' => $child_element['#utexas_fca_add_link_value']])) {
        $variables['button']['#value'] = t('@add_another', ['@add_another' => $child_element['#utexas_fca_add_link_value']]);
      }
    }
  }
}
