<?php

/**
 * @file
 * Provides the base content type component for the Events add-on.
 */

use Drupal\utevent\Permissions;

/**
 * Implements hook_modules_installed().
 */
function utevent_modules_installed($modules, $is_syncing) {

  $roles = Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  /** @var Drupal\user\Entity\Role $role */
  foreach ($roles as $role_id => $role) {
    $role_permissions = $role->getPermissions();
    foreach ($role_permissions as $permission) {
      if ($permission == 'create utevent_event content') {
        Permissions::assignPermissions('editor', $role_id);
        Drupal::messenger()->addMessage(t('Event scheduling permissions set for %role role.', [
          '%role' => $role->label(),
        ]));
      }
    }
  }
}
