<?php

/**
 * @file
 * UTexas instagram API .module file.
 */

use Drupal\utexas_instagram_api\UTexasInstagramApi;

/**
 * Implements hook_cron().
 */
function utexas_instagram_api_cron() {
  // On every cron run, request a new long-lived token using the stored
  // refresh token. These tokens expire every 60 days for security reasons.
  // Cron runs hourly on Pantheon, so there will always be a valid token.
  $accounts = \Drupal::entityTypeManager()->getStorage('utexas_ig_auth')->loadMultiple();
  foreach ($accounts as $account) {
    $instagram_request = new UTexasInstagramApi($account->id());
    $instagram_request->refreshGraphAccessToken();
  }
}
