<?php

/**
 * @file
 * Contains utprof demo content .module file.
 */

use Drupal\Core\File\FileSystemInterface;
use Drupal\Core\Language\Language;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;

/**
 * Helper function to create a media item.
 *
 * @param array $image_metadata
 *   Key-value pair for a media item.
 *
 * @return int
 *   The media MID.
 */
function _utprof_demo_content_create_media(array $image_metadata) {
  /** @var \Drupal\file\FileRepositoryInterface $file_repository */
  $file_repository = \Drupal::service('file.repository');
  $file_system = \Drupal::service('file_system');
  $filedir = 'public://utexas_devel/';
  $file_system->prepareDirectory($filedir, FileSystemInterface::CREATE_DIRECTORY);
  $image = File::create();
  $image->setFileUri($image_metadata['filepath']);
  $image->setOwnerId(\Drupal::currentUser()->id());
  $image->setMimeType(\Drupal::service('file.mime_type.guesser')->guessMimeType($image_metadata['filepath']));
  $image->setFileName(basename($image_metadata['filepath']));
  $destination_dir = 'public://generated_sample';
  $file_system->prepareDirectory($destination_dir, FileSystemInterface::CREATE_DIRECTORY);
  $destination = $destination_dir . '/' . basename($image_metadata['filepath']);
  $file = $file_repository->copy($image, $destination);
  $image_media = Media::create([
    'name' => $image_metadata['filename'],
    'bundle' => 'utexas_image',
    'uid' => '1',
    'langcode' => Language::LANGCODE_NOT_SPECIFIED,
    'status' => '1',
    'field_utexas_media_image' => [
      'target_id' => $file->id(),
      'alt' => $image_metadata['alt_text'],
      'title' => $image_metadata['title_text'],
    ],
  ]);
  $image_media->save();
  return $image_media->id();
}

/**
 * Helper function to create a Profile node.
 *
 * @param array $data
 *   Key-value array of field data.
 */
function _utprof_demo_content_create_node(array $data) {
  $node = Node::create(['type' => 'utprof_profile']);
  $node->set('title', $data['title']);
  $node->set('uid', '1');
  foreach ($data['fields'] as $machine_name => $field_data) {
    $node->set($machine_name, $field_data);
  }
  foreach ($data['profile_groups'] as $group_name) {
    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')
      ->loadByProperties(['name' => $group_name, 'vid' => 'utprof_groups']);
    $group = reset($term);
    $group_tids[] = $group->id();
  }
  $node->set('field_utprof_profile_groups', $group_tids);
  if (isset($data['basic_media'])) {
    $media_mid = _utprof_demo_content_create_media($data['basic_media']);
    $node->set('field_utprof_basic_media', $media_mid);
  }
  $node->status = 1;
  $node->enforceIsNew();
  $node->save();
}
