<?php

/**
 * @file
 * Contains utexas_hero.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function utexas_hero_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the utexas_hero module.
    case 'help.page.utexas_hero':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines a compound field with media, heading, subheading, link, caption and credit.') . '</p>';
      return $output;

    default:
  }
}
