<?php

/**
 * @file
 * Profile base module installation file.
 */

/**
 * Implements hook_install().
 */
function utprof_install() {
  // Enable this add-on's read-only functionality. We do this in a
  // hook_install() implementation so that the module may be uninstalled.
  if (\Drupal::moduleHandler()->moduleExists('utprof_readonly') === FALSE) {
    \Drupal::service('module_installer')->install(['utprof_readonly']);
  }

  // Enable this add-on's dynamic overrides module. We do this here so that the
  // module may be uninstalled.
  if (\Drupal::moduleHandler()->moduleExists('utprof_overrides') === FALSE) {
    \Drupal::service('module_installer')->install(['utprof_overrides']);
  }
}

/**
 * Enable the utprof_readonly module.
 */
function utprof_update_8101() {
  // Enable this add-ons read-only functionality.
  if (\Drupal::moduleHandler()->moduleExists('utprof_readonly') === FALSE) {
    \Drupal::service('module_installer')->install(['utprof_readonly']);
  }
}

/**
 * Issue #308: HOTFIX: Allow field_utprof_basic_media node field to...
 */
function utprof_update_8102() {
  // Enable this add-on's dynamic overrides module.
  if (\Drupal::moduleHandler()->moduleExists('utprof_overrides') === FALSE) {
    \Drupal::service('module_installer')->install(['utprof_overrides']);
  }
}
