<?php

/**
 * @file
 * Provides the base content type component for the Profiles add-on.
 */

use Drupal\utprof\Permissions;

/**
 * Implements hook_modules_installed().
 */
function utprof_modules_installed($modules, $is_syncing) {

  // Add configuration for scheduled transitions.
  $config = \Drupal::configFactory()->getEditable('scheduled_transitions.settings');
  $bundles = $config->get('bundles') ?? [];
  $profile_bundle = ['entity_type' => 'node', 'bundle' => 'utprof_profile'];
  if (!in_array($profile_bundle, $bundles)) {
    $bundles[] = $profile_bundle;
    $config->set('bundles', $bundles)->save();
  }

  // Add permissions for scheduled transitions.
  $roles = Drupal::entityTypeManager()->getStorage('user_role')->loadMultiple();
  /** @var Drupal\user\Entity\Role $role */
  foreach ($roles as $role_id => $role) {
    $role_permissions = $role->getPermissions();
    foreach ($role_permissions as $permission) {
      if ($permission == 'create utprof_profile content') {
        Permissions::assignPermissions('editor', $role_id);
        Drupal::messenger()->addMessage(t('Profile scheduling permissions set for %role role.', [
          '%role' => $role->label(),
        ]));
      }
    }
  }
}
