<?php

/**
 * @file
 * UTexas instagram feature .module file.
 */

use Drupal\Core\Cache\Cache;
use Drupal\utexas_instagram\InstagramHelper;

/**
 * Implements hook_preprocess_block().
 */
function utexas_instagram_preprocess_block(&$variables) {
  if (isset($variables['content']['#block_content'])) {
    $block = $variables['content']['#block_content'];
    if ($block->bundle() !== 'utexas_instagram') {
      return;
    }
    $config_id = $block->get('field_utexas_instagram_acct')->getString();
    $variables['instagram_posts'] = InstagramHelper::render($config_id);
  }
}

/**
 * Implements hook_theme().
 *
 * Provide theme functions for blocks and pages needed for instagram.
 */
function utexas_instagram_theme($existing, $type, $theme, $path) {
  return [
    'utexas_instagram_feed_block' => [
      'variables' => [
        'attributes' => [],
        'instagram_posts' => [],
        'instagram_logo' => '',
        'instagram_handle' => '',
        'arrow_icon' => '',
      ],
    ],
    'utexas_instagram_feed_post' => [
      'variables' => [
        'attributes' => [],
        'pic_link' => '',
        'pic_src' => '',
        'pic_alt' => '',
        'pic_text' => '',
        'username' => '',
      ],
    ],
    'block__block_content__utexas_instagram' => [
      'template' => 'block--block-content--utexas-instagram',
      'base hook' => 'block',
    ],
    'block__inline_block__utexas_instagram' => [
      'template' => 'block--inline-block--utexas-instagram',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function utexas_instagram_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  if (isset($variables['elements']['content']['#block_content'])) {
    $block = $variables['elements']['content']['#block_content']->bundle();
    if ($block == "utexas_instagram") {
      $suggestions[] = "block__block_content__utexas_instagram";
    }
  }
}

/**
 * Implements hook_cron().
 */
function utexas_instagram_cron() {
  Cache::invalidateTags(['utexas_instagram_feed_blocks']);
}
