<?php

/**
 * @file
 * Defines simple utexas_paragraph_resource field types.
 */

/**
 * Implements hook_theme().
 */
function utexas_paragraph_resources_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_resource_container' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-resource-container',
    ],
    'paragraph__utexas_resource' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-resource',
    ],
  ];
}
