<?php

/**
 * @file
 * Defines simple utexas_paragraph_resource field types.
 */

use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function utexas_paragraph_resources_theme($existing, $type, $theme, $path) {
  return [
    'paragraph__utexas_resource_container' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-resource-container',
    ],
    'paragraph__utexas_resource' => [
      'base hook' => 'paragraph',
      'template' => 'paragraph--utexas-resource',
    ],
  ];
}

/**
 * Implements hook_field_widget_form_alter().
 */
function utexas_paragraph_resources_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
  $field = $context['items']->getFieldDefinition();
  // If there is a Resource Item paragraph iteration present, proceed.
  if ($field->getName() === "field_utexas_rc_items") {
    // If links field present on Resource, proceed.
    if (isset($element['subform']['field_utexas_resource_links'])) {
      // If the links field is set to unlimited iterations, proceed.
      if ($element['subform']['field_utexas_resource_links']['widget']['#cardinality'] === FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED) {
        $element['subform']['field_utexas_resource_links']['widget']['add_more']['#value'] = t('Add Another Link');
      }
    }
  }
}
