<?php

/**
 * @file
 * Contains utexas_featured_highlight.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\block\BlockForm;

/**
 * Implements hook_theme().
 */
function utexas_featured_highlight_theme($existing, $type, $theme, $path) {
  $variables = [
    'utexas_featured_highlight' => [
      'variables' => [
        'headline' => NULL,
        'media_identifier' => NULL,
        'media' => NULL,
        'date' => NULL,
        'copy' => NULL,
        'cta' => NULL,
        'style' => NULL,
      ],
      'template' => 'utexas-featured-highlight',
    ],
  ];
  return $variables;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_featured_highlight_form_layout_builder_update_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_featured_highlight_simplify_layout_form($form);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function utexas_featured_highlight_form_layout_builder_add_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _utexas_featured_highlight_simplify_layout_form($form);
}

/**
 * Helper function for Layout Builder form alters.
 */
function _utexas_featured_highlight_simplify_layout_form(&$form) {
  $is_featured_highlight = FALSE;
  // Check inline block view mode labels.
  if (isset($form['settings']['block_form'])) {
    $bundle = $form['settings']['block_form']['#block']->bundle();
    if ($bundle === 'utexas_featured_highlight') {
      $is_featured_highlight = TRUE;
    }
  }
  // Check reusable block view mode labels.
  if (isset($form['settings']['provider'])) {
    if ($form['settings']['provider']['#value'] == 'block_content') {
      $options = array_keys($form['settings']['view_mode']['#options']);
      if (in_array('utexas_featured_highlight_2', $options)) {
        $is_featured_highlight = TRUE;
      }
    }
  }
  if ($is_featured_highlight) {
    $form['settings']['view_mode']['#options'] = _update_featured_highlight_view_mode_labels($form['settings']['view_mode']['#options']);
  }
}

/**
 * Helper function for updating view mode labels.
 */
function _update_featured_highlight_view_mode_labels($options) {
  $formatterManager = \Drupal::service('plugin.manager.field.formatter');
  $definitions = $formatterManager->getDefinitions();
  $map = _utexas_featured_highlight_mapping_formatter_labels($definitions, 'utexas_featured_highlight');
  // Use keys from the available $options to get the matching key-value pairs.
  return array_intersect_key($map, $options);
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add logic to the place block form.
 */
function utexas_featured_highlight_form_block_form_alter(&$form, &$form_state, $form_id) {
  $bundle = FALSE;
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof BlockForm) {
    /** @var \Drupal\block\Entity\Block $entity */
    $entity = $form_object->getEntity();
    $uuid = $entity->getPlugin()->getDerivativeId();
    /** @var Drupal\block_content\Entity\BlockContent $block_content */
    if (isset($uuid)) {
      $block_content = \Drupal::service('entity.repository')->loadEntityByUuid('block_content', $uuid);
      if (method_exists($block_content, 'bundle')) {
        $bundle = $block_content->bundle();
        if ($bundle == 'utexas_featured_highlight') {
          $form['settings']['view_mode']['#options'] = _update_featured_highlight_view_mode_labels($form['settings']['view_mode']['#options']);
        }
      }
    }
  }
}

/**
 * Helper function for generating a mapped array of the widget formatter labels.
 */
function _utexas_featured_highlight_mapping_formatter_labels($definitions, $widget_type) {
  $map = [];
  foreach ($definitions as $key => $value) {
    if (strpos($key, $widget_type) !== FALSE) {
      $map[$key] = $definitions[$key]['label']->__toString();
    }
  }
  // Convert first key to "default" to be used by view modes.
  $map['default'] = $map[$widget_type];
  unset($map[$widget_type]);
  // Sort the array by machine name.
  asort($map);
  return $map;
}
