<?php

/**
 * @file
 * Install and update functions for UTexas Featured Highlight module.
 */

/**
 * Implements hook_install().
 */
function utexas_featured_highlight_install() {
  drupal_set_installed_schema_version('utexas_featured_highlight', '8101');
}

/**
 * Update configuration related to responsive image styles.
 */
function utexas_featured_highlight_update_8101() {
  \Drupal::service('features.manager')->import([
    'utexas_featured_highlight',
  ], TRUE);
}
