name: Create a multidev for testing
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'utdk_profile git branch to use'
        required: true
        type: string
env:
  BRANCH: ${{ github.event.inputs.branch }}
  SITE: 'utdkpr'
  REPO: 'utdk_profile'
jobs:
  multidevcreator:
    runs-on: [ wcs-gh-p02-group ]
    steps:
      - uses: actions/checkout@v3
      - name: CREATE A PANTHEON MULTIDEV
        id: createmultidev
        run: bash .github/workflows/scripts/create_multidev_from_pull_request.sh
