name: Delete existing multidev when a pull request gets closed.

on:
  # Triggers the workflow when a new commit is pushed to the HEAD ref of a pull request
  pull_request:
    types: [closed]
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BRANCH: ${{github.event.pull_request.head.ref}}
  SITE: 'utdkpr'

jobs:
  deletemultidev:
    runs-on: [ wcs-gh-p02-group ]
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Delete Pantheon multidev
        continue-on-error: true
        run: |
          cd .github/workflows/scripts/
          bash delete.sh
