name: Update an existing multidev when an open pull request gets updated.

on:
  # Triggers the workflow when a new commit is pushed to the HEAD ref of a pull request
  pull_request:
    types: [synchronize]

env:
  BRANCH: ${{github.event.pull_request.head.ref}}
  SITE: 'utdkpr'
  REPO: 'utdk_profile'

jobs:
  updatemultidev:
    runs-on: [ wcs-gh-p02-group ]
    continue-on-error: true
    steps:
      - name: Derive Pantheon multidev name
        id: set_multidev
        run: |
          BRANCH=${{github.event.pull_request.head.ref}}
          # Pantheon multidevs are limited to 11 characters.
          MULTIDEV=${BRANCH:0:11}
          echo "::set-output name=MULTIDEV::"${MULTIDEV}""

      - uses: actions/checkout@v3
      - name: Do the Composer build and deploy
        id: updatemultidev
        continue-on-error: true
        run: |
          cd .github/workflows/scripts/
          # Give sync to github.com a chance to complete.
          sleep 120
          # Run a composer update to get the latest hash for the branch.
          bash update.sh
          # Allow Pantheon to complete the build process.
          sleep 120
          # Re-install in case any of the new changes involve configuration.
          bash install.sh
